### ISSUE TITLE
API Auth Error 

### ISSUE THREAD

**Issue by jeylites** [lodev09/homebridge-tuya-smarthome#1]
Hey there, 

I gave the plugin a shot, the following appeared on the log despite having the right credentials.  Just wondering if I'm missing something here. 

Starting to advertise 'HB8-Tuya#8 51C3' using bonjour-hap backend!
[20/06/2021, 00:42:54] Homebridge v1.3.4 (HB8-Tuya#8) is running on port 51527.
[20/06/2021, 00:42:55] [TuyaSmartHome] ERR 2406: skill id invalid
[20/06/2021, 00:42:55] [TuyaSmartHome] Failed to authentcate API

**Config**

```
"bridge": {
        "name": "HB8-Tuya#8",
        "username": "0E:*******4:2B",
        "port": *****,
        "pin": "182******"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "options": {
                "username": "hey***@gmail.com",
                "password": "********1234",
                "countryCode": 6,
                "clientId": "5gk************0axq",
                "clientSecret": "3db8********************31d23",
                "baseUrl": "https://openapi.tuyaus.com",
                "schema": "smartlife"
            },
            "platform": "TuyaSmartHome"
        }
    ],
    "accessories": []
}
```

**Comment by jeylites** [comment]
To add to the above. Previously,  I was running Tuya Lan plugin and It worked with the same credentials.

**Comment by lodev09** [comment]
@jeylites the username/password must be the same as the account you logged in the smart life app and the `countryCode` should match as well.

Also, the "project" you create from tuya platform must be after May 25, 2021. See [this thread](https://github.com/tuya/tuya-homebridge/issues/14#issuecomment-850810887). You'll have to create another account since there's no way to delete an old development project :(
